# Change these first
owner: battlefield-portal-community # Your GitHub organization or username, where this repository lives
repo: bloodhound # The name of this repository

sites:
  - name: Battlefield Portal Library
    url: https://bfportal.gg
  - name: Battlefield Portal Library API
    url: https://api.bfportal.gg
assignees:
  - p0lygun


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bfportal.gg
  logoUrl: https://bfportal.gg/static/images/icon_portal_library_website.png
  name: Bloodhound
  introTitle: "Bloodhound is a uptime tracker for Battlefield Portal Library"
  navbar:
    - title: Status
      href: /
    - title: Battlefield Portal Library
      href: https://github.com/battlefield-portal-community/bfportal.gg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
NOTIFICATION_DISCORD: true
NOTIFICATION_DISCORD_WEBHOOK: true
NOTIFICATION_DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 1 1 *"
